import uuid
from typing import Optional, TYPE_CHECKING
from sqlalchemy import Enum, Float, ForeignKey, Index, Integer, JSON, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base, TimestampMixin, UUIDMixin
from app.db.models.enums import SummaryReviewStatus

if TYPE_CHECKING:
    from app.db.models.visit import Visit
    from app.db.models.user import User


class Summary(Base, UUIDMixin, TimestampMixin):
    """Clinical summary generated by AI and verified by a clinician."""

    __tablename__ = "summaries"

    visit_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("visits.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    payload_json: Mapped[dict] = mapped_column(
        JSON,
        default=lambda: {
            "patient_reported": {},
            "document_extracted": {},
            "ayush_assessment": {},
            "model_suggestions": [],
            "uncertainty_labels": [],
        },
        nullable=False,
    )
    confidence: Mapped[float] = mapped_column(Float, default=1.0, nullable=False)
    reviewed_by: Mapped[Optional[uuid.UUID]] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    review_status: Mapped[SummaryReviewStatus] = mapped_column(
        Enum(SummaryReviewStatus, name="summary_review_status_enum", native_enum=False),
        default=SummaryReviewStatus.DRAFT,
        nullable=False,
        index=True,
    )
    doctor_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Relationships
    visit: Mapped["Visit"] = relationship("Visit", back_populates="summaries")

    __table_args__ = (
        UniqueConstraint("visit_id", "version", name="uq_summaries_visit_version"),
        Index("ix_summaries_visit_review", "visit_id", "review_status"),
    )
