"""Add patient consent and user link

Revision ID: dd7368cf1c4d
Revises: 0001_initial_baseline
Create Date: 2026-08-29 18:00:31.751695+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd7368cf1c4d'
down_revision: Union[str, None] = '0001_initial_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('patients', sa.Column('consent_version', sa.String(length=20), nullable=True))
    op.add_column('patients', sa.Column('consent_timestamp', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('consent_language', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('consent_actor', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_patients_user_id'), 'patients', ['user_id'], unique=True)
    op.create_foreign_key(op.f('fk_patients_user_id_users'), 'patients', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_patients_user_id_users'), 'patients', type_='foreignkey')
    op.drop_index(op.f('ix_patients_user_id'), table_name='patients')
    op.drop_column('patients', 'consent_actor')
    op.drop_column('patients', 'consent_language')
    op.drop_column('patients', 'consent_timestamp')
    op.drop_column('patients', 'consent_version')
    op.drop_column('patients', 'user_id')
    # ### end Alembic commands ###
